In [1]:
import torch 
import numpy as np

In [4]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


## TRAINING DATA 

In [58]:
# inputs
Input = np.array([[73,21,23],
                 [553,32,231],
                 [34,26,76],
                 [78,61,89],
                 [29,260,2]], dtype = 'float32')

In [59]:
# targets
targets = np.array([[76,66],
                 [101,22],
                 [12,43],
                 [89,88],
                 [70,21]],dtype = 'float32')

In [60]:
# convert inputs and targets into tensors
Input = torch.from_numpy(np.asarray(Input))
targets= torch.from_numpy(np.asarray(targets))
#print(targets)


In [61]:
w =  torch.randn(2,3, requires_grad = True)
b =  torch.randn(2, requires_grad = True)

In [62]:
def model(x):
    return x @ w.t() +b

In [63]:
# generate predictions
preds = model(Input)
preds

tensor([[  -9.1065,  -41.0858],
        [ 122.5824, -436.5282],
        [  -1.3371,   31.7974],
        [ -38.0438,   31.7546],
        [-350.0685,  270.6819]], grad_fn=<AddBackward0>)

In [64]:
targets

tensor([[ 76.,  66.],
        [101.,  22.],
        [ 12.,  43.],
        [ 89.,  88.],
        [ 70.,  21.]])

## Loss Function 

In [65]:
## MSE function
def mse(a,b):
    diff = a - b
    return torch.sum(diff * diff) / diff.numel()

In [66]:
# compute loss
loss = mse(preds, targets)
loss

tensor(48783.0078, grad_fn=<DivBackward0>)

In [67]:
## Compute gradients
loss.backward()

In [68]:
print(w)
print(w.grad)

tensor([[ 0.1412, -1.3673,  0.3795],
        [-1.0608,  1.1519,  0.4859]], requires_grad=True)
tensor([[ -3364.5122, -23682.1699,  -2026.5132],
        [-51782.1172,   8854.6729, -22748.1738]])


In [69]:
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

## Training
- Train from initial 

In [70]:
preds = model(Input)


In [71]:
loss = mse(preds, targets)
print(loss)

tensor(48783.0078, grad_fn=<DivBackward0>)


In [72]:
loss.backward()

In [73]:
# Ajust weights and reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [74]:
# lets again calculate loss
preds = model(Input)
loss = mse(preds, targets)
loss

tensor(22664.9746, grad_fn=<DivBackward0>)

In [75]:
# To reduce the loss we again repeat the process
for i in range (100):
    preds = model(Input)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [76]:
preds = model(Input)
loss = mse(preds, targets)
loss

tensor(1087.1686, grad_fn=<DivBackward0>)

In [77]:
print(preds)
print(targets)

tensor([[ 17.3866,   1.1566],
        [111.6109,  33.0026],
        [ 37.7553,  58.8043],
        [ 54.1678,  61.2394],
        [ 79.0274,  29.5919]], grad_fn=<AddBackward0>)
tensor([[ 76.,  66.],
        [101.,  22.],
        [ 12.,  43.],
        [ 89.,  88.],
        [ 70.,  21.]])
